---
title: "Stat380 A2"
author: "Kerui Du"
date: "17/09/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
x=diag(3)+1
data=read.csv('Beach-Birds.csv')
```

# Q1

## 1a
```{r 1a}
x+matrix(rep(1:3,3),3,byrow = T)
```


## 1b
```{r 1b}
apply(x, 1, mean)
```

## 1c
```{r 1c}
x%*%matrix(rep(NA,9),3)
```

## 1d
```{r 1d}
x*.75
```


## 1e
```{r 1e}
solve(x)
```


# Q2
```{r Q2}
mod=par(mar=c(4,4,1,4))
plot.new()
plot.window(xlim = c(0,length(iris$Sepal.Length)),ylim = c(0,max(iris$Sepal.Length)))
points(1:length(iris$Sepal.Length),iris$Sepal.Length,col='blue',pch=16,cex=.8)
points(1:length(iris$Sepal.Length),iris$Petal.Length,col='red',pch=16,cex=.8)
axis(1)
axis(2,las=1)
axis(4,las=1)
box()
mtext('Individual',side = 1,line = 3,font = 1)
mtext('Sepal Length',side = 2,line = 3,col = 'blue',cex=.9)
mtext('Petal Length',side = 4,line = 3,col = 'red',cex=.9)
par(mod)
```


# Q3
```{r Q3}
stratified.hist= function(x , y, breaks = 20, xlab = NULL ,
                          ylab = NULL, main = "" , cex = 1)
{
  cols=hcl(h=c(230,145,90,351),c=64,l=75)
  y=factor(y)
  nms=levels(y)
  
  if (length(x) == length(data$flush.dist)){
    if (any(x<5)){
      if (length(y) == length(data$Species)){
      hist(x, breaks = breaks, col = cols[1], ylab = '', cex.axis = .75,
      main = main, xlab = '', xaxs='i', yaxs='i', ylim = c(0,48), las=1)
      
      hist(x[which(y!='Gull')], breaks = breaks, add = T, col = cols[2])

      hist(x[which(y%in%nms[3:4])],
           breaks = breaks, col = cols[3], add = T)

      hist(x[which(y=='Stint')], col = cols[4],
           xlim = c(0,20), add = T, breaks = 10)
      
      mtext('Flush.dist',side = 1,font = 1,line = 2.5)
      mtext('Frequency of Flush & Land distance',col='darkred',
            cex=1.47,outer=T,font=2,at=.535,line = .45)
      legend('topright',legend = nms,cex = .71,lty = 1,lwd=9.5,col = cols[1:4])
      box()
      }else {stop("unequal length data vectors")}
    }
    
    else{
      if (length(y) == length(data$Species)){
      hist(x, breaks = 20,col = cols[1], ylab = '', main = main, cex.axis = .75,
           xlab = '', xaxs = 'i', yaxs = 'i',las = 1, ylim = c(0,65))
      
      hist(x[which(y!='Gull')], breaks = breaks, add = T, col = cols[2])
      
      hist(x[which(y%in%nms[3:4])],
           col = cols[3], xlim = c(0,200), breaks = 10, add = T)
      
      hist(x[which(y=='Stint')],col = cols[4], xlim = c(0,200), add = T)

      mtext('Land.dist',side = 1,font = 1,line = 2.5)
      legend('topright',legend = nms,cex = .71,lty = 1,lwd=9.6,col = cols[1:4])
      box()
      }else {stop("unequal length data vectors")}
    }
  }
  
  else if (length(x) != length(data$flush.dist)){
    stop("unequal length data vectors")
  }
}

frame = par(mfrow=c(2,1),mar=c(5,2,0,0),oma=c(0,.2,2,1.5))

# appropriate parameter
stratified.hist(data$flush.dist,data$Species,breaks = 20, 
                xlab = NULL , ylab = NULL, main = "" , cex = 1)

stratified.hist(data$land.dist,data$Species,breaks = 20, 
                xlab = NULL , ylab = NULL, main = "" , cex = 1)

# inappropriate parameter
#stratified.hist(data$flush.dist[-1],data$Species,breaks = 20, 
#                xlab = NULL , ylab = NULL, main = "" , cex = 1)

par(frame)

```


















