---
title: "A3"
author: "Kerui Du"
date: "04/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r country}
urls = 'https://www.stat.auckland.ac.nz/~yongwang/stats380/population-by-country.html'
readin = readLines(urls)
col_names = strsplit(readin[11],'thead')[[1]][2] # all column names with uninterested parts
col_names_mod = strsplit(col_names,'</th> <th>')[[1]][-1] # split by common pattern

cols <- function(i) { # write function to remove each pattern
  if (i==1)
    col_names_mod[i]
  else if (i!=1&i!=11)
    sub('<br>','',col_names_mod[i])
  else if (i==11)
    sub('<.+$','',sub('<br>','',col_names_mod[i]))
}
col_name = sapply(1:11, cols) # all column names

interest = grep('/world-population/',readin) # return 11
sep_part = strsplit(readin[interest],'/world-population/')[[1]][-1:-2] # common pattern
info = sub('^.+population/\">','',sep_part) # all information we want
matrix = matrix(0,nr=235,nc=11) # create a matrix to help us build a data frame easily

country <- function(infos) { # write a function to extract all country names
  country = sub('<.+$', '', infos) # extract country 
  mod = grep('&amp;',country) # some countries need to be modified
  country[mod] <- sub('&amp;','&',country[mod]) # replace '&amp;' by '&'
  country[grep(';',country)] <- paste('Country', grep(';',country)) # modify some special letters
  country # our final result
}

info1 = sub('^.+;\">','',info)
info1 = strsplit(info1,'<td>') # separate rest allow us extract columns simply

for (i in 1:nrow(matrix)){
  matrix[i,1] = country(info)[i] # all Country with modification embed to 1st column
  for (j in 2:ncol(matrix)){
    index = j-1
    col = info1[[i]][index]
    if (index %in% c(2, 9, 10)){
      infos = sub(' %<.+$', '', col) # extract numbers with '%' and some may contain NA
      infos = sub('<.+$', '', infos) # get rid of unwanted
      infos = ifelse(infos=='N.A.',NA,infos) # get rid of unwanted
      matrix[i,j] = infos
    }
    else if (index %in% c(1, 3, 5, 6)){
      infos = sub('<.+$', '', col)  # get rid of unwanted
      infos = gsub(',','',infos)    # extract numbers with ',' but no NA 
      infos = ifelse(infos==" ",NA,infos) # get rid of unwanted
      matrix[i,j] = infos
    }
    else if (index %in% c(4, 7, 8)){
      infos = sub('<.+$', '', col)  # get rid of unwanted
      infos = gsub(',','',infos)    # extract numbers with ',' and it has NA
      infos = ifelse(infos=='N.A.',NA,infos) # get rid of unwanted
      matrix[i,j] = infos
    }
  }
}

population <- as.data.frame(apply(matrix[,2:11], 2, as.numeric)) # convert all characters to numeric
population = cbind(matrix[,1],population) # add the country column
colnames(population) <- col_name # final data frame

dim(population)
class(population)
head(population)
tail(population)
sum(population[[2]])

```


```{r population}

```

